name: package

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["tests"]
    branches:
      - '*'
      - '!master'
    types:
      - completed

jobs:

  actions-linux:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package Application
        uses: Dnawrkshp/pyinstaller-action@linux
        with:
          path: ClimateData
          spec: ClimateData.spec

  actions-windows:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Package Application
      uses: Dnawrkshp/pyinstaller-action@windows
      with:
        path: ClimateData
        spec: ClimateData.spec
